# Blueprint untuk deploy aplikasi Flask dengan database PostgreSQL di Render
services:
  # 1. Layanan untuk Database PostgreSQL
  - type: db  
    name: weather-db-postgres
    engine: postgres # <-- DITAMBAHKAN: Spesifikasikan engine database
    databaseName: weatherdb
    user: weatheruser
    plan: free
    postgresMajorVersion: 15

  # 2. Layanan untuk Aplikasi Web Flask (Bagian ini sudah benar)
  - type: web
    name: weather-prediction-app
    env: python
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL_FOR_RENDER
        fromDatabase:
          name: weather-db-postgres
          property: connectionString